### ISSUE TITLE
Power Line Communication support in Whitefield

### ISSUE THREAD

**Issue by nyrahul** [whitefield-framework/whitefield#101]
* Support Power line comm in Whitefield using [NS3-PLC](http://www.ece.ubc.ca/~faribaa/ns3_plc_software.htm) as backend
* Support for narrowband and wideband PLC
* Support for different PLC cable types

 [PR](https://github.com/ns3-plc-module/plc/pull/16) fixes PLC module for latest NS3 core.

**Comment by nyrahul** [comment]
## Tasklist
* [X] Integrating PLC in NS3
* [X] Configuration support in Whitefield
* [ ] Creating nodes/cables in Whitefield
* [ ] OAM support for PLC
* [ ] Testing

**Comment by weld10** [comment]
Hello Sir,

I just started using Whitefield for my simulation. I tried configuring PLC but it returned errors. Shall I import the PLC rep to NS3 platform?
Also, for the E2E delay used for UDP stats in RPL, why it always return zero values despite the DODAG is created?

Thanks very much

**Comment by nyrahul** [comment]
> I just started using Whitefield for my simulation. I tried configuring PLC but it returned errors. Shall I import the PLC rep to NS3 platform?
> Also, for the E2E delay used for UDP stats in RPL, why it always return zero values despite the DODAG is created?
> 

PLC support is not finished as yet. As you can see above in the (checkbox) tasklist, there is still a lot of work pending, but major technical risks are now mitigated.

Earlier I thought Whitefield will choose a given interface (802.15.4 or PLC) based on config during startup i.e., only one interface could be used, but later I decided to design in a way that both (or even more in future) interfaces could be used "simultaneously".

I am not sure about the E2E delay problem you are having. But if you are trying it on PLC then rest assured it won't work as of now. Only 802.15.4 is fully supported. If you are having problems with E2E delay with 802.15.4 then we can discuss that separately. Rest assured almost every experiment done in Whitefield needs E2E UDP delay and thus should work.

For PLC, stay posted here.
Tentative finish time is ~12 July.

**Comment by nyrahul** [comment]
@weld10 , meanwhile let me know what PLC configuration (as detailed as possible, including modulation scheme, cable types, outlets) you are looking for. I will consider this during implementation. Thanks.

**Comment by weld10** [comment]
I think the most common PLC configuration nowadays should support both PRIME and G3 standard.
Spectrum model, modulation scheme (OFDM, BPSK, ...), along with cable types supported in NS3 (underground and overhead cables) are important.

**Comment by nyrahul** [comment]
@weld10 PLC has multiple cable types. Is it possible that there are different cable types used between different pairs of nodes?
For e.g., `n1 <-----[AL3x95XLPE]---------> n2 <------------[NAYY50SE]--------> n3`, where AL3x95XLPE, NAYY50SE are different cable types. As per the NS3-PLC APIs this seems possible but there is no example depicting this.

**Comment by weld10** [comment]
@nyrahul Yes this is possible. I will share with you my realistic PLC map offline.

**Comment by nyrahul** [comment]
@weld10 The latest master now supports Power Line Communication. You can now fetch the latest master and check `config/wf_plc.cfg and config/plc_topology.cfg` for configuring your nodes.

**Comment by weld10** [comment]
@nyrahul Thanks very much and I am really grateful for your continuous support.

**Comment by Amrican10** [comment]
Hello Rahul,

I already started building my PLC network. As you know, the udp-server node
(DCU) may have many nodes connected to it (wired); like:

*plc_link[0]=1*    *//*
plc_link[1]=2
plc_link[2]=3
*plc_link[0]=4*   *//*

Does the limitation of multiple-interface in CONTIKI nodes prevent the
connection of two PLC links at the same time? This is because I received
errors when invoking wf_plc for the above config .....
Thanks.


‫في الأحد، 5 يوليو 2020 في 2:06 م تمت كتابة ما يلي بواسطة ‪Rahul Jadhav‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by nyrahul** [comment]
@weld10 You cannot have multiple plc_link from the same node. It is the same as using multiple interfaces and like I said Contiki/RIOT does not support multiple interfaces and thus won't be possible to handle it (at least currently).

I wished there could be a proper RPL implementation supporting multiple interfaces! Most of the RPL implementations currently are very simplistic, because they were meant to be operated on sensor nodes with few KBs of flash/RAM.

**Comment by nyrahul** [comment]
PLC mode is now available by default in Whitefield.
