### ISSUE TITLE
Whitefield can't run 2 instances from different users

### ISSUE THREAD

**Issue by philok93** [whitefield-framework/whitefield#108]
**Describe the bug**
When I tried to run whitefield from a different user in linux, I got this error:

```
INFO  00:00:00.000 [usock_init:66] USOCK binding to [/WHITEFIELD_0002ffff]
ERROR 00:00:00.000 [usock_init:70] bind failed errno=98
INFO  00:00:00.000 [usock_cleanup:85] closed commline unix sockets
```

**To Reproduce**
1. Start whitefield
2. Create a new user in linux
3. Try to run a new whitefield instance. You get an error and can't run it.

**Expected behavior**
It should allow a different instance of whitefield to run from different user. This will help to run simulations simultanously from the same linux machine.

**Comment by nyrahul** [comment]
@philok93 the issue is taken care of.

Note that I have made some changes to setup.sh. By default, it enables only contiki + ns3.

For using contiki-ng + ns3 ... you need to do `scripts/setup.sh --contiki-ng 1` ... ns3 is default enabled.

**Comment by nyrahul** [comment]
@philok93 Can you confirm if this is working ok for you? Thanks.

**Comment by philok93** [comment]
Yes, it works fine! Thanks a lot!
