### ISSUE TITLE
Support multiple PLC leaf nodes

### ISSUE THREAD

**Issue by Amrican10** [whitefield-framework/whitefield#111]
Is there anyway to enable multiple PLC leaf nodes. This will extremely affect the hops from each node to sink. 
Please, check the following config lines, I need node 4 to be a leaf node (beside node 6):

plc_link[0]=1     #server1
plc_link[1]=2
plc_link[2]=3,NAYY150SE
plc_link[3]=4
plc_link[4]=5   #why this connection is needed; start failed when I comment this line
plc_link[5]=6    #server2

nodeExec[0]=thirdparty/contiki/examples/ipv6/rpl-udp/udp-server.whitefield $NODEID
nodeExec[5]=thirdparty/contiki/examples/ipv6/rpl-udp/udp-server.whitefield $NODEID

**Comment by nyrahul** [comment]
Turns out that the NS3-PLC logic uses a graph for all the nodes/edges and it does not allow disjoint sets within the same graph.
I need to debug more and check if there is any way to handle this.
Any suggestions, welcome.

**Comment by Amrican10** [comment]
The *plc-test* example showed that multiple leaf nodes as well as multiple
interfaces and/or sinks are supported:

https://github.com/SabaFar/plc/blob/9e79ff4b04718463e3d9ed896e66e0dbf5f1a768/examples/plc-test.cc

It seems that PLC_Outlet enables multiple connections for all nodes and
PLC_ Tx/RxInterface enables bidirectional communication.

**Comment by nyrahul** [comment]
I tried this setup, i.e, if I dont add RX/TX interface. If I dont add the interfaces then the sendframe asserts. send needs an interface to be used.

I just added code for creating outlet for every node and then selectively adding TX/RX interfaces. Everything works fine but when the node tries to send a packet, it asserts for nodes who do not have an interface.

**Comment by nyrahul** [comment]
![image](https://user-images.githubusercontent.com/9133227/87848614-8d3ca900-c8ff-11ea-891b-ef7534c7f4d0.png)

This topology works for me. But surprisingly the upstream/downstream paths are not multihop. Can you try this in your env?

**Comment by Amrican10** [comment]
@nyrahul It works fine with me. You can merge the latest PLC updates to the Master for more flexible configuration. Thanks a lot.

**Comment by nyrahul** [comment]
Closing as the fix worked.
