### ISSUE TITLE
Support for different RPL objective functions

### ISSUE THREAD

**Issue by Amrican10** [whitefield-framework/whitefield#113]
Can Whitefield support different RPL objective functions (OFs)?

The current implementation supports only few OFs and cannot be configured through **project-conf.h.** The following repo uses different metrics and also additive OFs. I already used it using Cooja and it works fine.

https://github.com/Monica-/contiki_RPL_RFC6551

**Comment by nyrahul** [comment]
RPL OFs are to be supported in respective network stack implementation i.e., in Contiki, RIOT. Whitefield will automatically support all the OFs that are supported by respective stacklines. There is no change needed in Whitefield to support the OFs. Whitefield's MAC layer exports all the link layer feedback (LQI, RSSI, Num of retries per unicast packet) needed to support such OFs.

**Comment by nyrahul** [comment]
Nothing to fix here. RPL OFs have to be handled as part of the respective stackline implementations.
