### ISSUE TITLE
Whitefield Framework in my application

### ISSUE THREAD

**Issue by whoaminb** [whitefield-framework/whitefield#91]
I am running my application in whitefield framework.I face lot of error in making my application setup as per whitefield i corrected some of them but still i am not sure whether my application will work or not.
while running (./server.whitefield) The error i am facing right now is **incomplete argv set** what should be the second argument to pass while running the program.
and what change in should do in program setup(like setting /dev directory and making changes in main function) while using sensors.

![Capture](https://user-images.githubusercontent.com/28953899/70971137-431fea80-20c6-11ea-9f0c-d3ca5f18f3a4.JPG)

**Comment by nyrahul** [comment]
You cannot run the application from the command line .. You need to edit the config/wf.cfg file ... 
![image](https://user-images.githubusercontent.com/9133227/70974473-cb13ed80-20e2-11ea-865c-67ef90c21e7f.png)

This configuration file is used by `./invoke_whitefield.sh` script.

![image](https://user-images.githubusercontent.com/9133227/70974548-fa2a5f00-20e2-11ea-9c3b-a5e9294ad9ac.png)

You can also check the sample [demo video](https://vimeo.com/291555732) to understand invocation.
https://vimeo.com/291555732

**Comment by whoaminb** [comment]
what about running whitefield in raspberry pi loaded with wheezy rasbian?

**Comment by nyrahul** [comment]
> what about running whitefield in raspberry pi loaded with wheezy rasbian?

Is there a reason you use raspberry for simulation framework execution?
I have never tested whitefield on raspberry and am not sure why anyone would want to use rpi for simulation purposes.

**Comment by whoaminb** [comment]
ok can you tell me that in ipv6/rpl-udp/udp-server.c   there is code for button sensor activation how we can add real hardware setup like sensors and nodes to this program and make it run.

**Comment by nyrahul** [comment]
> ok can you tell me that in ipv6/rpl-udp/udp-server.c there is code for button sensor activation how we can add real hardware setup like sensors and nodes to this program and make it run.

To trigger any action on the node (button press or anything else), you can use the wfshell script to send the command to the node process. Currently I use this to query node's statistics such as ipv6/rpl/icmp send/rcv/drop packet status and for all other oam cmds.

Now if you need to trigger your own action then you can add your own `cmd_action_handler` in the [commands.c](https://github.com/whitefield-framework/contiki/blob/master/platform/whitefield/command.c). Add the ref in `PLAY_CMD(mbuf, cmd_action_handler)` in [cl_stackline_helpers.c](https://github.com/whitefield-framework/whitefield/blob/master/src/commline/cl_stackline_helpers.c).

After this you should be able to call the `cmd_action_handler` from wfshell using `scripts/wfshell.sh cmd_action_handler`

**Comment by nyrahul** [comment]
Closing as these were only queries.
