### ISSUE TITLE
Multiple BR/udp-servers in parallel

### ISSUE THREAD

**Issue by nyrahul** [whitefield-framework/whitefield#95]
A deployment may have multiple BRs, thus the tooling needs to consider this. `monitor.sh` is already changed to handle an argument which takes as an input br-nodeid and shows connectivity in context to it.

**Comment by nyrahul** [comment]
@philok93
The problem with plot-network seems to be contiki-ng specific.
Plot-network works by using `cmd_def_route` from contiki-ng.

Currently, the default route returned by contiki-ng seems to be incorrect.
![image](https://user-images.githubusercontent.com/9133227/80913645-be81f000-8d78-11ea-8c24-4261ac757f8b.png)

I use this API in contiki and contiki-ng to query the default route. For contiki-ng this doesn't seem to work!
![image](https://user-images.githubusercontent.com/9133227/80913650-cc377580-8d78-11ea-8425-8fdb5bb1e50a.png)

Do you know which is the right API for contiki-ng?

**Comment by philok93** [comment]
I found that you can use `uip_ds6_defrt_lookup(uip_ds6_defrt_choose())` to return the default route ip address. Check this shell commands:
https://github.com/contiki-ng/contiki-ng/blob/develop/os/services/shell/shell-commands.c#L632

I tried it and I notice that at start when network is not formed, the routes all show to node 1:
```
wfsh# cmd_def_route
sl_cmd "0:cmd_def_route"
fd00::1

sl_cmd "1:cmd_def_route"
fd00::1

sl_cmd "2:cmd_def_route"
fd00::1

sl_cmd "3:cmd_def_route"
fd00::1

sl_cmd "4:cmd_def_route"
fd00::1

sl_cmd "5:cmd_def_route"
fd00::1

sl_cmd "6:cmd_def_route"
fd00::1

sl_cmd "7:cmd_def_route"
fd00::1
```

Then, it is correct:
```
wfsh# cmd_def_route
sl_cmd "0:cmd_def_route"
fd00::1

sl_cmd "1:cmd_def_route"
fd00::1

sl_cmd "2:cmd_def_route"
fe80::302:304:506:1

sl_cmd "3:cmd_def_route"
fe80::302:304:506:0

sl_cmd "4:cmd_def_route"
fe80::302:304:506:0

sl_cmd "5:cmd_def_route"
fe80::302:304:506:0

sl_cmd "6:cmd_def_route"
fe80::302:304:506:0

sl_cmd "7:cmd_def_route"
fe80::302:304:506:0
```
```

**Comment by nyrahul** [comment]
It was never expected that a stackline will report a global IP prefix in default route. Contiki-ng should fix this.

Whitefield did not take into account network prefix while plotting graphs.
[Now it does](https://github.com/whitefield-framework/whitefield/commit/ff45b0bf8caa273be84fc7b5dfb341b7f507445f).
Also, nodes who are not connected will show up in the plots.
@philok93, this should work for you.

**Comment by philok93** [comment]
Yeah thanks a lot! Now works perfectly! :) If you can guide me how to make the graph (position based network graph ) a bit better tell me. I try to plot it but nodes overlap and need some space between them.

**Comment by nyrahul** [comment]
[Added](https://github.com/whitefield-framework/whitefield/commit/87769cdf5f562ae80e6f10742a122e6d89f73f54) a way to scale the position based graph.

Usage:
`./scripts/wfshell plot_network_graph tree.png pos.png scale=20`
Note the `scale=20` parameter scaling the `pos.png` by 20x.
`scale=` parameter is applicable only for position based graph.

Appreciate your offer for help but it was a small change in external scripts and hence decided to do it myself. Looking forward to any contribs while you do your experiments.

Hope it helps and thanks for constant feedback.

**Comment by philok93** [comment]
Thanks a lot for your improvement! I will try it and give you my feedback. It should work now.
I needed plotting the topology it to check how far each node is deployed from server because in random topology sometimes nodes don't connect and I believe that are far away.
I really appreciate your help and in my future works I will reference you.

**Comment by philok93** [comment]
I tried and this is the output with 22 nodes and scale=500:

![p11](https://user-images.githubusercontent.com/5327683/81088664-ef426080-8f03-11ea-9120-8f26bd4bf74a.png)

Is the x,y location of the nodes the real one coming from NS3? After executing the whitefield with random topology I got:
![p11](https://user-images.githubusercontent.com/5327683/81089031-7ee80f00-8f04-11ea-8a0c-ad268abc4575.png)

**Comment by nyrahul** [comment]
This looks like grid topology, certainly does not look random.
Can you share your config `wf.cfg`?
x,y location is the real location coming from ns3.

**Comment by philok93** [comment]
> This looks like grid topology, certainly does not look random.
> Can you share your config `wf.cfg`?
> x,y location is the real location coming from ns3.

Yes you are right, sorry my mistake I didn't change to randrect. I think plotting now works fine!

**Comment by nyrahul** [comment]
Handled.
