### ISSUE TITLE
Colorize the graph nodes based on nodeExec type

### ISSUE THREAD

**Issue by philok93** [whitefield-framework/whitefield#99]
**Is your feature request related to a problem? Please describe.**
When I run plot_network_graph command to show me the graph, it would be good if the nodes are colored based on the type on binary. See the example below.

**Describe the solution you'd like**
For example, in Cooja  you have topology graph like below
![testRoot](https://user-images.githubusercontent.com/5327683/83324054-30136800-a26b-11ea-8b69-659796f6b519.png)

The root (udp-server) is colored green, the udp-clients are colored yellow and other type of nodes are colored orange. This is good for the user to distinguish the nodes based on the binary and their number. In whitefield, it would be good to have the same logic so when you run the plot_network_graph, it would take the config file and for each node (nodeExec) defined, a color is assigned in the graph. At the end, a udp-client will have different color from udp-server node.

**Comment by nyrahul** [comment]
@philok93 I understand the default colors suck. You can set the colors yourself. Check the [PR]((https://github.com/whitefield-framework/whitefield/pull/100)) for help.
Share your snapshots and if you manage to get better colors then the defaults can be updated. 

![p](https://user-images.githubusercontent.com/9133227/83339155-98128e80-a2fd-11ea-9c49-8a1d089ead18.png)
![t](https://user-images.githubusercontent.com/9133227/83339157-9d6fd900-a2fd-11ea-88e5-a69dc1ce84d2.png)

**Comment by nyrahul** [comment]
@philok93 Wondering if this works for you and any feedback?

**Comment by philok93** [comment]
Hey @nyrahul , sorry for my late response. I just found time to test it. Thanks a lot works really well! The only question I have is, how can I call the get_node_attr.sh to color other types of nodes?

**Comment by nyrahul** [comment]
You can change the `get_node_color()` function in `get_node_attr.sh` according to your needs. This script is passed the node id as an input for which the node color is desired as output.

For e.g., let's assume you want to color the odd/even nodes differently ... you can use
```
get_node_color()
{
    color=blue # Even node's color
    [[ $(($1 % 2)) -ne 0 ]] && color=red # Odd node's color

    echo "{ \"color\": \"$color\" }"
}
```
You can query any node's properties using Linux commands or wfshell and use this to apply colors. 
Or simply you can set the color based on the passed node's ID.

In your first comment, you mentioned you want UDP-client in one color, UDP-server in another color and non-UDP nodes in yet another color. This can be easily achieved using:
```
get_node_color()
  {
      nexec=`$DIR/wfshell cmd_node_exec $1`
      bin=`basename "${nexec/ */}"`
      if [[ $bin =~ .*udp-server.* ]]; then
         color="red"
      elif [[ $bin =~ .*udp-client.* ]]; then
          color="green"
      else
          color="gray"
      fi
   
      echo "{ \"color\": \"$color\" }"
  }
```
I think the script is self-explanatory.

**Comment by philok93** [comment]
Thanks a lot for the explanation. It works as expected!

**Comment by nyrahul** [comment]
Closing. Feature/Enhancement added.
